In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('Customer_Car_Purchase.csv')

x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values


In [4]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)


In [5]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [ ]:
from sklearn.svm import SVC

classifier_linear = SVC(kernel='linear',random_state=0)
classifier_linear.fit(x_train,y_train)

classifier_rbf = SVC(kernel='rbf',random_state=0)
classifier_rbf.fit(x_train,y_train)

classifier_sigmoid = SVC(kernel='sigmoid',random_state=0)
classifier_sigmoid.fit(x_train,y_train)

classifier_poly = SVC(kernel='poly',random_state=0)
classifier_poly.fit(x_train,y_train)


#The portion below is for Support Vector Regression
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(x_train,y_train)

SVR()

In [9]:
y_pred_linear = classifier_linear.predict(x_test)
y_pred_rbf = classifier_rbf.predict(x_test)
y_pred_sigmoid = classifier_sigmoid.predict(x_test)
y_pred_poly = classifier_poly.predict(x_test)

#The snippet below is for prediction based on Support Vector Regression
y_pred_svr = regressor.predict(x_test)
a =[]
for i in range(len(y_pred_svr)):
    a.append([y_test[i],y_pred_svr[i]])

for i in a:
    print(i)


[0, 0.1647340115130303]
[0, -0.03959815050871984]
[0, 0.026178561320936322]
[0, 0.044563875531800634]
[0, -0.0776204665214052]
[0, 0.003955960309636741]
[0, 0.021292015982634416]
[1, 1.0241232813435084]
[0, 0.006624709807138474]
[0, 0.7097297093773024]
[0, -0.020447683374472336]
[0, -0.00954623804584076]
[0, -0.0919182360955233]
[0, 0.1214825668376146]
[0, -0.038359208931898814]
[0, 0.9091533272337767]
[0, 0.08136120652370438]
[0, -0.030582363008488378]
[1, 0.9232688653293648]
[0, 0.10571495665335429]
[0, -0.060363900919888636]
[1, 0.8803877011817222]
[0, 0.0855659889313437]
[1, 0.9915594419848124]
[0, 0.04830616800891585]
[1, 0.887609778309427]
[0, 0.1021612482834845]
[0, 0.03872598335709887]
[0, -0.09725434886314244]
[0, 0.1999166550634181]
[0, -0.030733736215260876]
[1, 0.12489698314877956]
[1, 0.9461676814012782]
[0, -0.0821673296445814]
[0, 0.00046620233325278537]
[0, 0.07754462575791954]
[0, -0.061581379302000694]
[0, -0.0385492087204774]
[0, -0.005308687784136068]
[1, 0.95504515

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

print("Metrics for Linear:")
print("Accuracy: ",accuracy_score(y_test,y_pred_linear))
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred_linear))
print('\n')
print("Metrics for RBF:")
print("Accuracy: ",accuracy_score(y_test,y_pred_rbf))
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred_rbf))
print('\n')
print("Metrics for Poly:")
print("Accuracy: ",accuracy_score(y_test,y_pred_poly))
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred_poly))
print('\n')
print("Metrics for Sigmoid:")
print("Accuracy: ",accuracy_score(y_test,y_pred_sigmoid))
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred_sigmoid))
# print('\n')
# print("Metrics for Support Vector Regression:")
# # print("Accuracy: ",accuracy_score(y_test,y_pred_svr))
# print("Confusion Matrix:")
# print(confusion_matrix(y_test,y_pred_svr))

Metrics for Linear:
Accuracy:  0.9125
Confusion Matrix:
[[57  1]
 [ 6 16]]


Metrics for RBF:
Accuracy:  0.95
Confusion Matrix:
[[55  3]
 [ 1 21]]


Metrics for Poly:
Accuracy:  0.9125
Confusion Matrix:
[[58  0]
 [ 7 15]]


Metrics for Sigmoid:
Accuracy:  0.8
Confusion Matrix:
[[50  8]
 [ 8 14]]


Metrics for Support Vector Regression:
Confusion Matrix:


ValueError: Classification metrics can't handle a mix of binary and continuous targets